__author__ = 'Taylan Sengul'

# =================== STATES ===================
MAIN_MENU_STATE = "MAIN_MENU_STATE"
INVENTORY_STATE = "INVENTORY_STATE"
GAME_OVER_STATE = "GAME_OVER_STATE"
MAP_STATE = "MAP_STATE"
TARGETING_STATE = "TARGETING_STATE"
# =================== SCREENS ===================
MAIN_SCREEN = "MAIN_SCREEN"
MAP_SCREEN = "MAP_SCREEN"
PLAYER_SCREEN = "PLAYER_SCREEN"
GAME_INFO_SCREEN = "GAME_INFO_SCREEN"
MESSAGES_SCREEN = "MESSAGES_SCREEN"
ENEMY_SCREEN = "ENEMY_SCREEN"
MAIN_MENU_SCREEN = "MAIN_MENU_SCREEN"
INVENTORY_MENU_SCREEN = "INVENTORY_MENU_SCREEN"
INVENTORY_DETAILS_SCREEN = "INVENTORY_DETAILS_SCREEN"
GAME_OVER_SCREEN = "GAME_OVER_SCREEN"
# =================== FONTS ===================
CONSOLE_FONT = "CONSOLE_FONT"
INVENTORY_FONT = "INVENTORY_FONT"
MAIN_MENU_FONT = "MAIN_MENU_FONT"
MAP_OBJECT_FONT = "MAP_OBJECT_FONT"
# =================== COLORS ===================
BLACK = (0, 0, 0)
BLUE = (17, 91, 184)
DARK_GRAY = (75, 75, 75)
GREEN = (96, 162, 110)
RED = (204, 0, 0)
WHITE = (255, 255, 255)
YELLOW = (255, 174, 0)
ColorID = dict(black=BLACK, blue=BLUE, dark_gray=DARK_GRAY, green=GREEN, red=RED, white=WHITE, yellow=YELLOW)
